### ISSUE TITLE
汉化统一管理一下

### ISSUE THREAD

**Issue by zhouchuanfu** [WangHL0927/grafana-chinese#12]
在教程里面把fork目标不是官网，而是你这边建立的目录，然后大家有汉化的也可以PR，这样你汉化不过来可以大家一起来汉化呀！

**Comment by WangHL0927** [comment]
6.x正在规划这些内容。

**Comment by zhouchuanfu** [comment]
我在github库里面找了一个新版本的库，汉化做了一部分，我感觉你们可以合作嘛，他那个没有知名度，但是做了一部分，这样大家也不需要做重复性的工作了，将时间用在更有意义的地方嘛。这是他的地址，我前两天也刚fork ，https://github.com/ericzzhou/grafana-chinese

**Comment by WangHL0927** [comment]
感谢建议，pr流程已在规划中， 跟随6.2.4 发布。
