### ISSUE TITLE
ubuntu版本下面编译之后打包的问题。

### ISSUE THREAD

**Issue by zhouchuanfu** [WangHL0927/grafana-chinese#13]
我这边遇到一个问题，系统是ubuntu 18.04.03版本，经历千辛万苦终于编译成功，模拟运行可以了，但是想要打包的话就没有办法了是么，我这边提示要安装rpm_build ，但是rpm_build没有deb版本的，只有rpm版本的。

**Comment by WangHL0927** [comment]
抱歉，这个问题我没法解答，没有研究过整体发布流程。
