### ISSUE TITLE
没理解 按哪个步骤来实现汉化？

### ISSUE THREAD

**Issue by carlgan** [WangHL0927/grafana-chinese#14]
楼主，你好~
若我要对已安装好的6.4.3 的grafana 做汉化， 是不是 的完全按照 你的“Grafana汉化笔记.md”  步骤 来执行？
不太理解 还要准备开发环境和创建git库？ 求指导！！！ 
是否有更简单的汉化 步骤？

**Comment by WangHL0927** [comment]
这个教程是让你创建汉化版本的，编译完成后自行替换。

**Comment by carlgan** [comment]
收到 谢谢~ 若遇到问题 我在QQ群里 提问吧。
