### ISSUE TITLE
关于汉化

### ISSUE THREAD

**Issue by meterXu** [WangHL0927/grafana-chinese#3]
汉化的内容有点少，但有人做这个工作就很不错了，希望作者加油出一个完整的汉化

**Comment by WangHL0927** [comment]
谢谢您的支持，最近比较忙，我会尽量加快进度。

**Comment by zhongqin0820** [comment]
我想请教一下,关于汉化,主要修改的是哪部分代码?
我原以为它是利用i18n插件?可以直接根据相应的json文件做汉化.
不过,我没找到,作者可以分享一下是怎么做的汉化吗? @WangHL0927

**Comment by WangHL0927** [comment]
您好， @zhongqin0820 
简略说一下步骤，拿到Grafana官方源码，前端页面的内容在public/app文件夹下，汉化里面的内容然后用官方的方式重新打包发布即可。
最近在搬家，后续详细步骤我会更新一片文章来介绍我的操作步骤。
敬请关注项目主页更新。

**Comment by zhongqin0820** [comment]
@WangHL0927 非常感谢你的解答
我的疑问是，汉化过程是硬编码吗？即直接在源文件中修改，而不是类似利用i18n这样的插件利用外部语言配置文件汉化？（我懂的知识有限，可能有说错的地方请见谅）

**Comment by WangHL0927** [comment]
@zhongqin0820 以我目前折腾的来看确实是分散在源码里的，官方似乎并没有做多语种的打算。

**Comment by WangHL0927** [comment]
@meterXu @zhongqin0820 汉化教程已更新 [https://wanghualong.cn/archives/44/](https://wanghualong.cn/archives/44/)

**Comment by zhongqin0820** [comment]
@WangHL0927 谢谢

**Comment by meterXu** [comment]
@WangHL0927 666
