### ISSUE TITLE
能展示一下你那边现在汉化的界面吗

### ISSUE THREAD

**Issue by chinaxushi** [WangHL0927/grafana-chinese#5]
能展示一下你那边现在汉化的界面吗，我这边替换了public后，感觉只有很少的地方汉化了，怀疑是我自己没弄好。如果能在说明里放几张正常的汉化图就好了。

**Comment by WangHL0927** [comment]
确实是有点少，能显示出汉化内容说明已经替换成功了。
7月底要赶一个dl，一直没有后续更新，很抱歉。TAT
