### ISSUE TITLE
汉化

### ISSUE THREAD

**Issue by webliuxiang** [WangHL0927/grafana-chinese#6]
![image](https://user-images.githubusercontent.com/25944130/43892821-a0da3e66-9bff-11e8-8447-bf3eeb66653f.png)这一版是还没开始汉化吗？

**Comment by zhongqin0820** [comment]
@webliuxiang 你能看到的应该就是作者目前汉化完的，没有汉化的就是还没汉化的，也可以参考一下我汉化的：https://github.com/XiaoguTech/grafana

仅供参考
